version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vinintel
    ports: ["5433:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-10T18-41-49Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - miniodata:/data
volumes:
  dbdata:
  miniodata:
